version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo

jobs:
  install-deps:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

  test1:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas - parte 1
          command: |
            pip install -r requirements.txt
            pytest test.py -k "suma"

  test2:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas - parte 2
          command: |
            pip install -r requirements.txt
            pytest test.py -k "resta"

  lint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Análisis con flake8
          command: |
            pip install -r requirements.txt
            flake8 .

workflows:
  version: 2
  flujo:
    jobs:
      - install-deps
      - test1:
          requires:
            - install-deps
      - test2:
          requires:
            - install-deps
      - lint:
          requires:
            - install-deps
