version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  instalar-dependencias:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            pip install -r requirements.txt
            pip install flake8
      - persist_to_workspace:
          root: .
          paths:
            - .

  test-suma:
    executor: python-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Ejecutar prueba suma
          command: |
            pip install -r requirements.txt
            pytest test.py -k "suma"

  test-resta:
    executor: python-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Ejecutar prueba resta
          command: |
            pip install -r requirements.txt
            pytest test.py -k "resta"

  flake8-analysis:
    executor: python-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Ejecutar flake8
          command: |
            pip install -r requirements.txt
            flake8 .

  notify:
    executor: python-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Notificación Telegram
          command: |
            curl -s -X POST https://api.telegram.org/bot7534877343:AAEemGGoNy9A2b6irCXCt6VCYISGEnyZzl8/sendMessage \
              -d chat_id=1122221631 \
              -d text="🔔 Finalizó el pipeline JenkinsEx1. Revisa el estado en CircleCI."

workflows:
  version: 2
  flujo:
    jobs:
      - instalar-dependencias
      - test-suma:
          requires:
            - instalar-dependencias
      - test-resta:
          requires:
            - instalar-dependencias
      - flake8-analysis:
          requires:
            - instalar-dependencias
      - notify:
          requires:
            - test-suma
            - test-resta
            - flake8-analysis
