version: 2.1

executors:
  default:
    docker:
      - image: cimg/python:3.11

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Simular fallo pero continuar
          command: |
            echo "❌ Simulando un fallo"
            echo "failed" > status.txt
            false || true  # No detiene el job
      - persist_to_workspace:
          root: .
          paths:
            - status.txt

  notify:
    executor: default
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Enviar notificación a Telegram
          command: |
            STATUS=$(cat /workspace/status.txt)
            if [ "$STATUS" = "failed" ]; then
              curl -s -X POST "https://api.telegram.org/bot7534877343:AAEemGGoNy9A2b6irCXCt6VCYISGEnyZzl8/sendMessage" \
              -d chat_id=1122221631 \
              -d text="🚨 El job *build* ha fallado en CircleCI."
            else
              curl -s -X POST "https://api.telegram.org/bot7534877343:AAEemGGoNy9A2b6irCXCt6VCYISGEnyZzl8/sendMessage" \
              -d chat_id=1122221631 \
              -d text="✅ El job *build* fue exitoso en CircleCI."
            fi

workflows:
  version: 2
  flujo:
    jobs:
      - build
      - notify:
          requires:
            - build
